class ApartmentsController < ApplicationController

  def index
    @apts = Apartment.all
  end

  def new #renders form
    if current_user && current_user.is_a_broker
      @new_apt = Apartment.new
    else
      redirect_to renter_home_path
    end
  end

  def create #parses params hash (generated by user)
    @new_apt = Apartment.create(params[:apartment])
    redirect_to apartments_path
    # render json: params
    # {"utf8":"\u2713","authenticity_token":"XmZjgA/lnAWP3W+Ua6P52N1xj/CORwlxLyGCyTuY+w4=","apartment":{"price":"1500","bedrooms":"1","bathrooms":"1","street":"blah","city":"blah","state":"blah","zipcode":"blah","region":"blah","longitude":"blah","latitude":"blah","photo":"blah"},"commit":"submit","action":"create","controller":"apartments"}
  end

  def edit
    if current_user && current_user.is_a_broker
      #feed the apt id into the view yadig
      @apt = Apartment.find(params[:id])
    else
      redirect_to renter_home_path
    end
  end

  def update 
    @apt = Apartment.find(params[:id])
    @apt.update_attributes(params[:apartment])
    @apt.save

    redirect_to apartments_path
  end

  def show
    @apt = Apartment.find(params[:id])
  end

  def destroy
    @apt = Apartment.find(params[:id])
    @apt.destroy

    redirect_to apartments_path
  end

  # THIS IS IN FAVORITES CONTROLLER too ugh
  def favorite
    user_id = params[:user_id]
    apartment_id = params[:apartment_id]

    @user = User.find(user_id)
    apartment = Apartment.find(apartment_id)

    favorite = Favorite.create(user: user, apartment: apartment)

    redirect_to renter_home_path
  end

end




















